# Generated by Django 5.1.1 on 2024-11-23 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_b_items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemb',
            old_name='details',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='itemb',
            old_name='title',
            new_name='name',
        ),
    ]
